import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Suspense } from "react";



export const metadata = {
  title: "VerseAI",
  description: "Generated by create next app",
};

const inter=Inter({subsets:["latin"]});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'inter.className'}>
        <Header/>
          <main className="min-h-screen bg-gradient-to-b from-green-50 to-white">{children}</main>
          <footer className="bg-green-100 py-12">
              <div className="container mx-auto px-4 text-center text-gray-600">
                <p>Made with 💗 by VerseAI</p>
              </div>
          </footer>
      </body>
    </html>
  );
}
